### PR TITLE
[Logger] Aligned jsdoc for compliant with http://usejsdoc.org/

### PR DESCRIPTION
**Pull request by stefano-rainieri**
fixed jsdoc for the @jymfony/logger.

### CODE REVIEW

**Comment by alekitto** [comment]
Thanks, we should fix other components' jsdoc too. I'll open an issue for that.
However I think we should keep the `integer` type specification instead of using `number`. It is more clear on how to use it and what kind of variabile the method expects. What do you think about it?

**Comment by stefano-rainieri** [comment]
Yes you're right, `integer` could be clearer than `number` . But as explained in [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures) docs there is no integer data type supported by javascript. They're all treated as `number`.
I think we could keep `number` to be compliant with jsdoc, and then to specify the type of the number like `integer` or `float` in the comment after the jsdoc _param annotation_.

**Comment by massimilianobraglia** [comment]
Good point @stefano-rainieri. How would you write down the jsdoc?
Something like this?

```js
/**
 * @param {number} iAmANumber - integer
 **/
funcWithNumberArgs(iAmANumber) {
}
```

**Comment by stefano-rainieri** [comment]
Yes exactly @massimilianobraglia , something like you've written 👍

**Comment by massimilianobraglia** [comment]
Then it LGTM 👍 
it should not be more verbose than this for me

**Comment by alekitto** [comment]
I don’t totally agree with that. While the integer and float types don’t exist in js, they are well-known types and recognized by IDEs and code inspectors. They are even used in the jsdoc package source code and could be useful to statically detect errors in parameters and function calls.

**Comment by massimilianobraglia** [comment]
I did not know about this feature from IDEs and code inspectors. Then for me it's ok to keep those types

**Comment by alekitto** [comment]
Recap:

- Use `{int}` or `{float}` where a specialized type is needed. `{number}` only if it doesn't matter.
- Array as `{type[]}`
- `@returns` has the trailing "s"
- No dash before the param description
- `[name = defaultValue]` for optional parameters

Did I miss something?

**Comment by massimilianobraglia** [comment]
I think you covered everything. @stefano-rainieri can you update your PR?

**Comment by massimilianobraglia** [comment]
http://usejsdoc.org/tags-inheritdoc.html
FYI `@inheritdoc` is fully lower case. 😄

**Comment by stefano-rainieri** [comment]
fixed jsdoc for this PR

**Comment by alekitto** [comment]
Thanks

**Pull request merged**
